{
  "run": {
    # timeout for analysis, e.g. 30s, 5m, default is 1m
    "deadline": "3m",
    "skip-dirs": ["checkers/rules"],
  },
  "fast": false,
  "linters": {
    "enable": [
      "deadcode",
      "errcheck",
      "gas",
      "gocritic",
      "gofmt",
      "goimports",
      "govet",
      "gosimple",
      "ineffassign",
      "megacheck",
      "misspell",
      "nakedret",
      "staticcheck",
      "typecheck",
      "unconvert",
      "unparam",
      "unused",
      "varcheck",
    ],
  },
  "disable": [
    "depguard",
    "dupl",
    "gocyclo",
    "interfacer",
    "lll",
    "maligned",
    "prealloc",
  ],
}
