
# Main Options

#- Example mode: server or client (server,client) [server]
MODE                 ?= server
#- Generate and print config definition in given format and exit (default: '', means skip) (,json,md,mk) []
CONFIG_GEN           ?=
#- Dump config dest filename (string) []
CONFIG_DUMP          ?=

# HTTP Options

#- Addr and port which server listens at (string) [:8080]
HTTP_LISTEN          ?= :8080
#- HTTP Request Header for remote IP (string) [X-Real-IP]
HTTP_IP_HEADER       ?= X-Real-IP
#- HTTP Request Header for username (string) [X-Username]
HTTP_USER_HEADER     ?= X-Username
#- HTTP access log filename (default: STDOUT, '-' means disable) (string) []
HTTP_ACCESS_LOG      ?=
#- Add ETAG in HTTP response (bool) [false]
HTTP_ETAG            ?= false

# HTTPS Options

#- CertFile for serving HTTPS instead HTTP (string) []
HTTP_TLS_CERT        ?=
#- KeyFile for serving HTTPS instead HTTP (string) []
HTTP_TLS_KEY         ?=

# Client Options

#- HTTP server URL (string) [http://localhost:8080/demo]
CLIENT_URL           ?= http://localhost:8080/demo
#- HTTP request timeout (time.Duration) [3s]
CLIENT_TIMEOUT       ?= 3s

# Logging Options

#- Show debug info (bool) [false]
LOG_DEBUG            ?= false
#- Output format (default: '', means use text if DEBUG) (,text,json) []
LOG_FORMAT           ?=
#- Time format for text output (string) [2006-01-02 15:04:05.000]
LOG_TIME_FORMAT      ?= 2006-01-02 15:04:05.000
#- Log destination (default: '', means STDERR) (string) []
LOG_DEST             ?=

# OpenTelemetry Options

#- OTLP gRPC endpoint URL (string) [http://localhost:4317]
OTEL_EXPORTER_OTLP_ENDPOINT ?= http://localhost:4317
#- Unique service instance id, e.g. pod name, pod UID, hostname, or container id (string) []
OTEL_SERVICE_INSTANCE_ID ?=
#- OTLP metrics export interval (time.Duration) [10s]
OTEL_METRIC_INTERVAL ?= 10s
#- OpenTelemetry shutdown timeout (time.Duration) [5s]
OTEL_SHUTDOWN_TIMEOUT ?= 5s
#- Enable traces export (bool) [false]
OTEL_ENABLE_TRACES   ?= false
#- Enable metrics export (bool) [false]
OTEL_ENABLE_METRICS  ?= false
#- Enable Go runtime metrics collection (bool) [false]
OTEL_ENABLE_GO_RUNTIME_METRICS ?= false
